version : 2

models:
  - name : dim_listings_cleansed
    description : cleansed table which contains airbnb listing
    columns:
    - name : listing_id
      description : primary key for listing
      tests :
        - unique
        - not_null
    - name : host_id
      description : host's id. refernces the host table.
      tests:
        - not_null
        - relationships :
            to : ref('dim_hosts_cleansed')
            field : host_id
    - name : room_type
      description : type of the room / apartment.
      tests :
        - accepted_values :
            values : ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']
    - name : minimum_nights
      description : '{{ doc ("dim_listing_cleansed_minimum_nights")}}'
      tests :
        - positive_value