version : 2

models:
  - name : dim_listings_cleansed
    description : cleansed table which contains airbnb listing
    columns:
    - name : listing_id
      description : primary key for listing
      tests :
        - unique
        - not_null
    - name : host_id
      description : host's id. refernces the host table.
      tests:
        - not_null
        - relationships :
            to : ref('dim_hosts_cleansed')
            field : host_id
    - name : room_type
      description : type of the room / apartment.
      tests :
        - accepted_values :
            values : ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']
    - name : minimum_nights
      description : '{{ doc ("dim_listing_cleansed_minimum_nights")}}'
      tests :
        - positive_value
  - name : dim_listings_w_hosts
    tests :
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model : source('airbnb','listings')
    columns:
      - name : price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile : .99
              min_value : 50
              max_value : 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value : 5000
              config :
                severity : warn 
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type : number 